/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Liberi Arcano (https://sketchfab.com/LiberiArcano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3december-2021-day-18-astronaut-40f22d473c2e41868794254068fb94a5
Title: 3December 2021 Day 18: Astronaut
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Astronaut(props) {
    const { nodes, materials } = useGLTF('/models/3december_2021_day_18_astronaut-transformed (1).glb')
    const modelRef = useRef();
    useFrame(() => {
        modelRef.current.rotation.y += 0.007;

    })
    return (
        <group {...props} dispose={null}
            ref={modelRef}
            scale={[0.9, 0.9, 0.9]}
            rotation={[0.4, -1, 0]}
            position={[0, -0.9, 0]}
        >
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
                geometry={nodes.Object_7.geometry}
                material={materials.Suit_Base}
                skeleton={nodes.Object_7.skeleton}
                position={[0, 0, -0.413]}
                scale={0.4}
            />
            <skinnedMesh
                geometry={nodes.Object_8.geometry}
                material={materials.Suit_Details}
                skeleton={nodes.Object_8.skeleton}
                position={[0, 0, -0.413]}
                scale={0.4}
            />
            <skinnedMesh
                geometry={nodes.Object_9.geometry}
                material={materials.Suit_Visor}
                skeleton={nodes.Object_9.skeleton}
                position={[0, 0, -0.413]}
                scale={0.4}
            />
        </group>
    )
}

useGLTF.preload('/models/3december_2021_day_18_astronaut-transformed (1).glb')